config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :rooms, only: [:index, :show]
  resources :posts, only: [:create]

   root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
   has_many :posts

   
end
		

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
    def after_sign_in_path_for(resource)
    '/rooms'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id 
		@post.save
		redirect_to @post.room
	end

	private
	def post_params
		params.require(:post).permit( :body,:user_id,:room_id)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :authenticate_user!
	def index
		@rooms = Room.all
	end
	
	def show
		@room = Room.find(params[:id])
		@post = Post.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1.intro hello!

app/views/layouts/_nav.html.haml
%nav.main-nav
	%ul
		%li=link_to "rooms", (rooms_path)
		-if user_signed_in?
			%li=current_user.username
			%li=link_to "sign out", (destroy_user_session_path), :method => :delete
		-else 
			%li=link_to "sign in",(new_user_session_path)
			%li=link_to "sign up", (new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Anyone
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    =render 'layouts/nav'
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/rooms/index.html.haml
%h1 Rooms index

- @rooms.each do |room|
	=link_to room.name, room_path(room.id)

app/views/rooms/show.html.haml
%h1=@room.name

= simple_form_for @post do |f|
	=f.input :body, label: false
	=f.hidden_field :room_id, value: @room.id
	=f.button :submit

%ul
	- @room.posts.each do |post|
		%li
			=post.body 
			%span=post.user.username
	